backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "."

collections:
  - name: "help" # Used in routes, e.g., /admin/collections/blog
    label: "Help" # Used in the UI
    folder: "content/help" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "use-cases" # Used in routes, e.g., /admin/collections/blog
    label: "Use Cases" # Used in the UI
    folder: "content/use-cases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ" # Used in the UI
    folder: "content/faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "guides_en" # Used in routes, e.g., /admin/collections/blog
    label: "Guides - English" # Used in the UI
    folder: "content/guides" # The path to the folder where the documents are stored
    filter: {field: "language", value: "en"}
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"], default: ["en"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "guides_fr" # Used in routes, e.g., /admin/collections/blog
    label: "Guides - French" # Used in the UI
    folder: "content/guides" # The path to the folder where the documents are stored
    filter: {field: "language", value: "fr"}
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}+{{language}}" # Filename template, !!! '+' will be replaced by '.'
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"], default: ["fr"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Ajit", "Raksha", "Tarun", "Manoj"]}
      - {label: "Weight", name: "weight", widget: "number", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
